# Generated by Django 3.1.3 on 2020-11-15 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='tipo_card',
            new_name='tipo',
        ),
    ]
