# Generated by Django 3.1.3 on 2020-11-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0002_auto_20201115_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.URLField(default='#'),
        ),
    ]
