# Generated by Django 3.1.3 on 2020-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bender', '0003_card_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='imagem',
            field=models.URLField(default='#'),
        ),
    ]
