# Generated by Django 3.1.3 on 2020-11-21 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('fonte', models.CharField(max_length=500)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField()),
                ('link', models.URLField(default='#')),
                ('imagem', models.URLField(default='#')),
            ],
        ),
    ]
